repos:
# sort imports
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

# check style and quality
- repo: https://github.com/PyCQA/flake8
  rev: '6.1.0'
  hooks:
    - id: flake8
      args: [--ignore=E203]

# code formatter
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=79]

# linter
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        args: ['--disable=E0401,  C0103, R0913']